# Stage 1: Build an Angular Docker Image
FROM node as build

WORKDIR /app

COPY package*.json /app/

RUN npm install

COPY . /app

ARG configuration=production

RUN npm run build -- --configuration $configuration

# Stage 2, use the compiled app, ready for production with Nginx
FROM nginx

COPY --from=build /app/dist/xbrl-forge/browser/ /usr/share/nginx/html

COPY docker_nginx.conf /etc/nginx/conf.d/default.conf